# Generated by Django 5.0.1 on 2024-04-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(max_length=32, null=True, verbose_name="管理员名称"),
                ),
                (
                    "admin_password",
                    models.CharField(max_length=32, null=True, verbose_name="管理员密码"),
                ),
                ("role", models.IntegerField(default=1, verbose_name="角色")),
                ("status", models.IntegerField(default=1, verbose_name="账号状态")),
                ("groupid", models.IntegerField(default=1, verbose_name="组ID")),
            ],
        ),
        migrations.CreateModel(
            name="Jobinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=200, null=True, verbose_name="工作名称"),
                ),
                (
                    "job_area",
                    models.CharField(max_length=200, null=True, verbose_name="工作地点"),
                ),
                (
                    "salary_bot",
                    models.CharField(max_length=200, null=True, verbose_name="最低薪资"),
                ),
                (
                    "salary_top",
                    models.CharField(max_length=200, null=True, verbose_name="最高薪资"),
                ),
                (
                    "year",
                    models.CharField(max_length=200, null=True, verbose_name="工作经验年限"),
                ),
                (
                    "education",
                    models.CharField(max_length=200, null=True, verbose_name="受教育水平"),
                ),
                (
                    "company_title",
                    models.CharField(max_length=200, null=True, verbose_name="公司名称"),
                ),
                (
                    "company_info",
                    models.CharField(max_length=200, null=True, verbose_name="公司规模"),
                ),
                (
                    "skill",
                    models.CharField(max_length=200, null=True, verbose_name="技能要求"),
                ),
                (
                    "publis_name",
                    models.CharField(max_length=200, null=True, verbose_name="发布者"),
                ),
                (
                    "welfare",
                    models.CharField(max_length=200, null=True, verbose_name="福利待遇"),
                ),
                (
                    "type",
                    models.CharField(max_length=200, null=True, verbose_name="职业类型"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=32, null=True, unique=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=16, null=True, verbose_name="密码"),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=64, null=True, unique=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=64, null=True, unique=True, verbose_name="手机号"
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        null=True,
                        verbose_name="QQ号",
                    ),
                ),
                (
                    "wechat",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="微信号",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="收货地址",
                    ),
                ),
                (
                    "work",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="工作单位",
                    ),
                ),
                ("role", models.IntegerField(default=0, verbose_name="角色")),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        default="这个人很懒，不爱写简介",
                        max_length=300,
                        null=True,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "pic",
                    models.CharField(
                        default="/static/user_default.png",
                        max_length=300,
                        verbose_name="头像",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="账号状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后登录时间"),
                ),
            ],
        ),
    ]
